language: objective-c

branches:
only:
- master

xcode_project: RomanNumeralConverter.xcodeproj

xcode_scheme: RomanNumeralConverterTests

osx_image: beta-xcode6.3

xcode_sdk: iphonesimulator8.3

script:
- xcodebuild clean build test -project RomanNumeralConverter.xcodeproj -scheme RomanNumeralConverterTests -destination 'platform=iOS Simulator,name=iPhone 5'
