language: objective-c

branches:
only:
- master

xcode_project: RomanNumeralConverter.xcodeproj

xcode_scheme: RomanNumeralConverter

osx_image: beta-xcode7.2

xcode_sdk: iphonesimulator9.2

script:
- xcodebuild clean build test -project RomanNumeralConverter.xcodeproj -scheme RomanNumeralConverter -destination 'platform=iOS Simulator,name=iPhone 5'
