language: objective-c

branches:
only:
- master

xcode_project: Roman Numeral Converter.xcodeproj
xcode_scheme: Roman Numeral Converter
osx_image: beta-xcode6.3
xcode_sdk: iphonesimulator8.3

script:
- xcodebuild clean build test -project Roman\ Numeral\ Converter.xcodeproj -scheme Roman\ Numeral\ Converter -destination 'platform=iOS Simulator,name=iPhone 5'
